### ISSUE TITLE
Wrong folder

### ISSUE THREAD

**Issue by brianteeman** [RickR2H/cassiopeia_child#1]
Great idea to make this - thanks

I have it all installed and when I make a change in /home/brian/leadershape.brianstest.site/media/templates/site/cassiopeia_child/scss/template.scss

the sass watch sees the change etc but the compiled css are created in the scss folder and not the css folder

What have I missed?
```

Change detected - 10/19/2022, 10:53:17 PM
template.scss
--------------------
Autoprefix warning
/home/brian/leadershape.brianstest.site/media/templates/site/cassiopeia_child/scss/template.css:2409:3
Replace color-adjust to print-color-adjust. The color-adjust shorthand is currently deprecated.
--------------------
Generated:
/home/brian/leadershape.brianstest.site/media/templates/site/cassiopeia_child/scss/template.css.map
/home/brian/leadershape.brianstest.site/media/templates/site/cassiopeia_child/scss/template.css
```

**Comment by brianteeman** [comment]
I found out how to fix it. It was because on a remote vs code session it doesnt read the settings.json unless its local

**Comment by RickR2H** [comment]
Great you did find a fix! If you need help feel free to contact me on Glip.
